# Generated by Django 6.1.1 on 2026-10-05 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Kaiser Permanente', 'Kaiser Permanente'), ('IEHP', 'IEHP'), ('Medicare', 'Medicare'), ('Medi-Cal', 'Medi-Cal'), ('Blue Shield', 'Blue Shield'), ('Anthem Blue Cross', 'Anthem Blue Cross'), ('Aetna', 'Aetna')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=50)),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.insurance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.CharField(choices=[('MD', 'MD'), ('DO', 'DO'), ('NP', 'NP'), ('PA', 'PA')], max_length=25)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Podiatry', 'Podiatry')], max_length=50)),
                ('accepted_insurance', models.ManyToManyField(related_name='providers', to='core.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_time', models.CharField(choices=[('Same Day', 'Same Day'), ('One Day', 'One Day'), ('Two Days', 'Two Days'), ('Three Days', 'Three Days'), ('Four Days', 'Four Days'), ('Five Days', 'Five Days'), ('Six Days', 'Six Days'), ('One Week', 'One Week'), ('Two Weeks', 'Two Weeks'), ('Three Weeks', 'Three Weeks')], max_length=25)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_date', models.DateField()),
                ('referral_number', models.PositiveIntegerField(unique=True)),
                ('requested_specialty', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Podiatry', 'Podiatry')], max_length=50)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Accepted', 'Accepted')], default='Ready', max_length=15)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_cost', models.CharField(choices=[('$0', '$0'), ('$35', '$35'), ('$65', '$65'), ('$85', '$85'), ('$100', '$100'), ('$150', '$150'), ('$275', '$275')], max_length=15)),
                ('appointment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appointmentinfo')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insurance')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appointment_info', 'insurance'), name='unique_appointment_insurance_cost')],
            },
        ),
    ]
