# Generated by Django 6.1.1 on 2026-10-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.CharField(choices=[('MD', 'MD'), ('DO', 'DO'), ('NP', 'NP'), ('PA', 'PA')], max_length=25)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('ORTHOPEDICS', 'Orthopedics'), ('DERMATOLOGY', 'Dermatology'), ('NEUROLOGY', 'Neurology'), ('PODIATRY', 'Podiatry')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='ref_date',
            new_name='referral_date',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
